### ISSUE TITLE
how to implement for file_uploader

### ISSUE THREAD

**Issue by riyosan** [crxi/multipage_streamlit#1]
Thank you very much, this multipage_streamlit really helped me, but i have another problem. When I apply file_uploader and display the contents of the csv that I uploaded on page A, and I go to page B and when I switch to page A then the file I uploaded earlier will disappear and also not display the contents of the csv

**Comment by crxi** [comment]
Hi @riyosan, I've answered you here: https://github.com/streamlit/streamlit/issues/3925#issuecomment-1100056591 as I think it is more of a streamlit restriction and not something that multipage-streamlit can resolve easily.
